### PR TITLE
Landing page wireframe

### PR DESCRIPTION
**Pull request by Avnish5**
Landing page wireframe

### CODE REVIEW

**Comment by Avnish5** [comment]
@Swarnimashukla Kindly check it and merge it mam.

**Comment by Swarnimashukla** [comment]
@Avnish5  its  in master branch directly, can you make it to resource branch please

**Comment by Avnish5** [comment]
@Swarnimashukla Mam now i have change the resources as branch.
Kindly check and merge it.

**Comment by suyashgautam** [comment]
Hey @Avnish5 There are 10 commits in this PR, can you please squash the commits only we would be able to merge this PR.

**Pull request closed without merging**
