### PR TITLE
Added the landing page design 

### PR DESCRIPTION
**Pull request by shristi99**
Resolved Issue #119

### CODE REVIEW

**Review by Swarnimashukla — APPROVED** [review]

**Review by Swarnimashukla — COMMENTED** [review]
@shristi99  could you export images from figma in png and upload here as files

**Comment by shristi99** [comment]
Rollcall-landing-page

**Comment by shristi99** [comment]
Rollcall-landing-page

**Comment by Swarnimashukla** [comment]
@shristi99  hey actually there is some issue in converting the fig file from this pr that's why it would be better to have a pr with image in png/jpeg itself it will be easy to develop in that case

**Comment by shristi99** [comment]
So you are saying to make another pr?

**Comment by shristi99** [comment]
So are you saying to make another pr?

**Comment by Swarnimashukla** [comment]
> So are you saying to make another pr?

yes that would be better

**Comment by shristi99** [comment]
Done!  You can close this pr mam.

**Pull request closed without merging**
