### PR TITLE
Created CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by i-aayush711**

### CODE REVIEW

**Comment by suyashgautam** [comment]
Hey @i-aayush711 kindly squash the commits.

**Comment by i-aayush711** [comment]
> Hey @i-aayush711 kindly squash the commits.

Hey what do you mean by squashing? Could you tell?

**Comment by ashutosh-cusat** [comment]
please assign me i solve this issue @Swarnimashukla

**Comment by Swarnimashukla** [comment]
@i-aayush711  please go through this https://davidwalsh.name/squash-commits-git

**Pull request closed without merging**
