### PR TITLE
RollCall_footer

### PR DESCRIPTION
**Pull request by Abhishekkr93**
## Related Issuse

- Added Footer for Rollcall Website(sections that include here e.g. Copyright, Social media, T&C)

Closes: #118 

#### Describe the changes you've made
Added code of Footer Section for Rollcall Website via Rollcall_footer file with index.html and style.css
Footer (sections that include here e.g. Copyright, Social media, T&C.)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|          changes          |
signal-2021-04-06-183043

### CODE REVIEW

**Comment by SKAUL05** [comment]
@Abhishekkr93 I see some changes in workflow and python files in this PR.
I don't think u need to change them, pls check your PR again and only include relevant files.

**Review by SKAUL05 — COMMENTED** [review]
@Abhishekkr93  I see some changes in workflow and python files in this PR.
I don't think u need to change them, pls check your PR again and only include relevant files.

**Comment by Abhishekkr93** [comment]
In which file sir? 
No sir, I only made a folder rollcall_footer then I added two file name index.html & style.css? 

So, I need to make a fresh pull request now? @SKAUL05

**Comment by SKAUL05** [comment]
@Abhishekkr93 It's showing around 28 files changed.
Either you can remove changes to the unknown files or create a new PR

**Comment by Abhishekkr93** [comment]
okay sir, I will make a new PR. closing this. @SKAUL05

**Comment by Abhishekkr93** [comment]
will making new PR.

**Pull request closed without merging**
