### PR TITLE
Image Classification using CNN

### PR DESCRIPTION
**Pull request by ParthSingh0506**
## Related Image Classification using CNN

- I have created Image classification using CNN
- 
Closes: #[issue number that will be closed through this PR]

Describe the changes you've made

->The idea behind this is that our model will be able to classify the image of male and female with accuracy of above 91 % . As it is a Automatic attendance system the system should also be capable to classify the students by sending the images to our neural network and by that NN will classify the images .

->Added Image-Classification.py file the CNN file
->Added network_image,json file of the CNN model such that it can be used either on website or an application in short words it is ready for deployment
->Added the Dataset that has been used for training as well as testing
->Added the weights.hdf5 the weight of the CNN

## Checklist:

<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by ParthSingh0506** [comment]
@Swarnimashukla Check this PR

**Comment by Swarnimashukla** [comment]
@ParthSingh0506  Can you make this pr in a separate branch not directly in master branch , create a new branch also can you explain how come there are 5000+ file changes and what's there in it ?

**Comment by ParthSingh0506** [comment]
@Swarnimashukla I have not created the PR in master branch I have created it separately only . The reason for 5000+ file changes is that the dataset have  more than 55,000 images that are used for training and testing so 5,000+ means in this branch more than 5000+ new files have been added . So the dataset is also present in the "Image-Classification" folder that's why it is showing more than 5000+ new files have been added .

**Comment by ParthSingh0506** [comment]
@Swarnimashukla kindly merge this branch to the master. If you have any problem with this PR do let me know .

**Pull request closed without merging**
