### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by Akash20x**
This pull request closes issue: #32 

Add issue templates for proposal, feature, and documentation.

### CODE REVIEW

**Review by SKAUL05 — APPROVED** [review]
LGTM :)

**Comment by Akash20x** [comment]
Please merge my pull request

**Comment by suyashgautam** [comment]
Hello @Akash20x The PR is good but can you squash the commits. Since there are 7 commits so we cant merge it as of now.

**Comment by Akash20x** [comment]
> Hello @Akash20x The PR is good but can you squash the commits. Since there are 7 commits so we cant merge it as of now.

What you mean to squash the commit

**Comment by Swarnimashukla** [comment]
@Akash20x  please go through this https://davidwalsh.name/squash-commits-git

**Comment by Akash20x** [comment]
I send another pull request with same files and all check are pass in that PR.
Closes this PR.

**Pull request closed without merging**
