### PR TITLE
added IA for ROLLCALL, issue-#28

### PR DESCRIPTION
**Pull request by Asmita-si**
I have added a file named "IA_Asmita-si.jpg" under issue #28 which is a flowchart/ IA for a website, ROLLCALL.

### CODE REVIEW

**Comment by Asmita-si** [comment]
@Swarnimashukla  Do I need to squash it?

**Comment by Swarnimashukla** [comment]
> @Swarnimashukla Do I need to squash it?

yes

**Review by bhubesh757 — APPROVED** [review]

**Comment by Asmita-si** [comment]
@Swarnimashukla  When I do rebase, only the first few commits I am able to see in sublime. The other commits including mine are not visible. So I am not able to squash it. Please help.

**Comment by Swarnimashukla** [comment]
> @Swarnimashukla When I do rebase, only the first few commits I am able to see in sublime. The other commits including mine are not visible. So I am not able to squash it. Please help.

did you tried solution given on discord ?

**Comment by Asmita-si** [comment]
@Swarnimashukla  yes, but it didn't solve my problem. I tried both "git rebase -i HEAD~11 --autostash" & "git rebase -i HEAD~11". In both cases, I am getting the same result. Only the first few commits are visible in sublime. The other commits including mine are not visible. So I am not able to squash it. Please help. I am attaching an image.
sc6

**Pull request closed without merging**
