### PR TITLE
Modified Logo Design

### PR DESCRIPTION
**Pull request by deeptea22**
## Related Issuse

Issue #1 - Have modified the logo design according to your suggestions and added in the Resources folder. 

Closes: #1 

#### Describe the changes you've made

Modified the logo design.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
Logo_Design_Deepthi

### CODE REVIEW

**Comment by Swarnimashukla** [comment]
@deeptea22  please squash your commits , it should be 1 commit only , refer to steps present in README.md file

**Comment by deeptea22** [comment]
I have followed the exact steps of the README file and have made only one commit. Even when i try to squash my commits, only one commit is displayed - which is the only commit i made. @Swarnimashukla

**Comment by suyashgautam** [comment]
Hey @deeptea22 If you are facing any trouble in squashing the commits, I would suggest closing this PR and create another one that would be easy for you.

**Comment by deeptea22** [comment]
Okay i will try that. Thank you.

**Pull request closed without merging**
