### PR TITLE
landing page

### PR DESCRIPTION
**Pull request by Avnish5**
I have created the landing page and make the PR request.
Kindly check it @Swarnimashukla 
#2

### CODE REVIEW

**Comment by Swarnimashukla** [comment]
Hey @Avnish5  can you share a screenshot of Landing page here

**Comment by Avnish5** [comment]
ROLLCALL - Google Chrome 15-03-2021 22_25_05

ROLLCALL - Google Chrome 15-03-2021 22_25_17
ROLLCALL - Google Chrome 15-03-2021 22_25_27
ROLLCALL - Google Chrome 15-03-2021 22_25_39

ROLLCALL - Google Chrome 15-03-2021 22_25_57

@Swarnimashukla Mam this the all the images of the whole landing page.

**Comment by suyashgautam** [comment]
Hey @Avnish5 At this point we just need wireframes for the landing page we don't want the code as of now. The development part will be assigned later once the Wireframes is selected by the project admin.

**Comment by Avnish5** [comment]
@suyashgautam Ok sir so can i create the wireframe now.If you allow me

**Pull request closed without merging**
